apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: acme-issuer
spec:
  acme:
    email: <your-email@example.com>  # Replace with your email
    privateKeySecretRef:
      name: acme-issuer-account-key  # Secret that will store the ACME private key
    solvers:
      - dns01:
          digitalocean:
            tokenSecretRef:
              name: digitalocean-api-token-secret  # Secret containing the API token
              key: api-token  # Key inside the secret holding the API token

